# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:latest
#    restart: always
    environment:
      POSTGRES_USER: amarcele
      POSTGRES_PASSWORD: qwertyui
      POSTGRES_DB: samplegres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  urlcoin:
    environment:
      DB_USAGE: 'true'
    build : .
    depends_on :
      - db
    ports:
      - 8080:8080

volumes:
  db_data: