// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package module

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserManagmentClient is the client API for UserManagment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserManagmentClient interface {
	Create(ctx context.Context, in *URL, opts ...grpc.CallOption) (*ShortURL, error)
	Get(ctx context.Context, in *ShortURL, opts ...grpc.CallOption) (*URL, error)
}

type userManagmentClient struct {
	cc grpc.ClientConnInterface
}

func NewUserManagmentClient(cc grpc.ClientConnInterface) UserManagmentClient {
	return &userManagmentClient{cc}
}

func (c *userManagmentClient) Create(ctx context.Context, in *URL, opts ...grpc.CallOption) (*ShortURL, error) {
	out := new(ShortURL)
	err := c.cc.Invoke(ctx, "/modulegrpc.UserManagment/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagmentClient) Get(ctx context.Context, in *ShortURL, opts ...grpc.CallOption) (*URL, error) {
	out := new(URL)
	err := c.cc.Invoke(ctx, "/modulegrpc.UserManagment/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserManagmentServer is the server API for UserManagment service.
// All implementations must embed UnimplementedUserManagmentServer
// for forward compatibility
type UserManagmentServer interface {
	Create(context.Context, *URL) (*ShortURL, error)
	Get(context.Context, *ShortURL) (*URL, error)
	mustEmbedUnimplementedUserManagmentServer()
}

// UnimplementedUserManagmentServer must be embedded to have forward compatible implementations.
type UnimplementedUserManagmentServer struct {
}

func (UnimplementedUserManagmentServer) Create(context.Context, *URL) (*ShortURL, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedUserManagmentServer) Get(context.Context, *ShortURL) (*URL, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedUserManagmentServer) mustEmbedUnimplementedUserManagmentServer() {}

// UnsafeUserManagmentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserManagmentServer will
// result in compilation errors.
type UnsafeUserManagmentServer interface {
	mustEmbedUnimplementedUserManagmentServer()
}

func RegisterUserManagmentServer(s grpc.ServiceRegistrar, srv UserManagmentServer) {
	s.RegisterService(&UserManagment_ServiceDesc, srv)
}

func _UserManagment_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(URL)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagmentServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/modulegrpc.UserManagment/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagmentServer).Create(ctx, req.(*URL))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagment_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortURL)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagmentServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/modulegrpc.UserManagment/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagmentServer).Get(ctx, req.(*ShortURL))
	}
	return interceptor(ctx, in, info, handler)
}

// UserManagment_ServiceDesc is the grpc.ServiceDesc for UserManagment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserManagment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "modulegrpc.UserManagment",
	HandlerType: (*UserManagmentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UserManagment_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _UserManagment_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modulegrpc/modulegrpc.proto",
}
